FROM ubuntu:latest

RUN apt-get update && apt-get install -y apache2 libapache2-mod-wsgi-py3 nano

COPY capstone_UI.conf /etc/apache2/sites-available/000-default.conf

COPY . /var/www/html/capstone_UI
WORKDIR /var/www/html/capstone_UI

EXPOSE 80

CMD ["apache2ctl", "-D", "FOREGROUND"]
