# Generated by Django 5.0.1 on 2024-03-25 22:01

import capstone_UI_app.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('eye', models.IntegerField(choices=[(0, 'Left Eye'), (1, 'Right Eye')], default=0)),
            ],
        ),
        migrations.CreateModel(
            name='PreprocessedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=capstone_UI_app.models.overwrite_filename)),
                ('eye', models.IntegerField(choices=[(0, 'Left Eye'), (1, 'Right Eye')], default=0)),
                ('original_image', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preprocessed_image', to='capstone_UI_app.uploadedimage')),
            ],
        ),
    ]
