# Generated by Django 5.0.1 on 2024-03-25 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone_UI_app', '0002_remove_preprocessedimage_eye_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='preprocessedimage',
            name='eye',
            field=models.IntegerField(choices=[(0, 'Left Eye'), (1, 'Right Eye')], default=0),
        ),
        migrations.AddField(
            model_name='uploadedimage',
            name='eye',
            field=models.IntegerField(choices=[(0, 'Left Eye'), (1, 'Right Eye')], default=0),
        ),
    ]
