# Generated by Django 5.0.1 on 2024-03-25 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capstone_UI_app', '0003_preprocessedimage_eye_uploadedimage_eye'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preprocessedimage',
            name='eye',
        ),
        migrations.RemoveField(
            model_name='uploadedimage',
            name='eye',
        ),
    ]
