# Generated by Django 5.0.1 on 2024-02-25 23:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone_UI_app', '0005_alter_uploadedimage_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreprocessedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='preprocessed_images/')),
                ('original_image', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preprocessed_image', to='capstone_UI_app.uploadedimage')),
            ],
        ),
    ]
