# Generated by Django 5.0.1 on 2024-03-04 18:42

import capstone_UI_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone_UI_app', '0006_preprocessedimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preprocessedimage',
            name='image',
            field=models.ImageField(upload_to=capstone_UI_app.models.overwrite_filename),
        ),
    ]
